data_path: /home/pandu/Panresearch/ConditionalNeuralField/data/3D_periodic_hill/Case3_periodichill/output.npy
load_data_fn: load_periodic_hill_flow

save_path: UnconditionalDiffusionTraining_and_Generation/data/case3_test
coor_path: /home/pandu/Panresearch/ConditionalNeuralField/data/3D_periodic_hill/Case3_periodichill/coords.npy
lumped_latent: True

normalizer:
  method: '-11'
  dim: 0
batch_size: 100
test_batch_size: 100

multiGPU: 2
readin_data_shape: "t N c"
batch_shape: "t N c"

hidden_size: 256
epochs: 30000

loss_fn: MSELoss
test_criteria: rMAE
save_every: 200

dims: 2

NF:
  name: SIRENAutodecoder_film
  in_coord_features: 2
  out_features: 2
  num_hidden_layers: 17
  hidden_features: 256

lr:
  nf: 1.e-4
  latents: 1.e-5